version: '3.1'

services:

  db:
    build:
      dockerfile: Dockerfile.db
      context: .
    restart: always
    volumes:
      - data-mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codepush
    networks:
      - app-sync-net

  redis:
    image: docker.io/library/redis:4.0.11-alpine
    volumes:
      - data-redis:/data
    ports:
      - 6379:6379
    networks:
      - app-sync-net

  adminer:
    image: docker.io/library/adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-sync-net

  appsync:
    build: .
    restart: always
    volumes:
      - data-storage:/data/storage
      - data-tmp:/data/tmp
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    environment:
      DOWNLOAD_URL: "http://localhost:3000/download"
      JWT_TOKEN: "Tc4nNI7lJLFwqnPOu9YLttJNx2hWFWwaq2PLKLXhcMRTf23pWRnQ3kiTwjujEWf"
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "codepush"
      STORAGE_DIR: "/data/storage"
      DATA_DIR: "/data/tmp"
      NODE_ENV: "production"
      CONFIG_FILE: "/opt/nativescript-app-sync-server/config/config.js"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    networks:
      - app-sync-net

volumes:
  data-storage:
  data-tmp:
  data-mysql:
  data-redis:

networks:
  app-sync-net: 
